function NVM = getNVMMapping

NVM.mapping = { ...
 [1]   [5] ' ' '3rd Ventricle	 ' ; ...
 [2]   [5] ' ' '4th Ventricle	 '; ...
 [3]   [6] ' ' 'Right Accumbens Area	 '; ...
 [4]   [6] ' ' 'Left Accumbens Area	'; ...
 [5]   [6] ' ' 'Right Amygdala	 '; ...
 [6]   [6] ' ' 'Left Amygdala	 '; ...
 [7]   [6] ' ' 'Brain Stem	 '; ...
 [8]   [6] ' ' 'Right Caudate	 '; ...
 [9]   [6] ' ' 'Left Caudate	 '; ...
 [10]  [6] ' ' 'Right Cerebellum Exterior	 '; ...
 [11]  [6] ' ' 'Left Cerebellum Exterior	 '; ...
 [12]  [7] ' ' 'Right Cerebellum White Matter	 '; ...
 [13]  [7] ' ' 'Left Cerebellum White Matter	 '; ...
 [14]  [7] ' ' 'Right Cerebral White Matter	 '; ...
 [15]  [7] ' ' 'Left Cerebral White Matter	 '; ...
 [16]  [5] ' ' 'CSF	'; ...
 [17]  [4] ' ' 'Right Hippocampus	 '; ...
 [18]  [4] ' ' 'Left Hippocampus	 '; ...
 [19]  [5] ' ' 'Right Inf Lat Vent	 '; ...
 [20]  [5] ' ' 'Left Inf Lat Vent	 '; ...
 [21]  [5] ' ' 'Right Lateral Ventricle	'; ...
 [22]  [5] ' ' 'Left Lateral Ventricle	 '; ...
 [23]  [6] ' ' 'Right Pallidum	'; ...
 [24]  [6] ' ' 'Left Pallidum	 '; ...
 [25]  [6] ' ' 'Right Putamen	 '; ...
 [26]  [6] ' ' 'Left Putamen	 '; ...
 [27]  [6] ' ' 'Right Thalamus Proper	'; ...
 [28]  [6] ' ' 'Left Thalamus Proper	'; ...
 [29]  [6] ' ' 'Right Ventral DC	 '; ...
 [30]  [6] ' ' 'Left Ventral DC	 '; ...
 [31]  [6] ' ' 'Optic Chiasm	 '; ...
 [32]  [6] ' ' 'Cerebellar Vermal Lobules I-V	 '; ...
 [33]  [6] ' ' 'Cerebellar Vermal Lobules VI-VII	 '; ...
 [34]  [6] ' ' 'Cerebellar Vermal Lobules VIII-X	 '; ...
 [35]  [6] ' ' 'Left Basal Forebrain	 '; ...
 [36]  [6] ' ' 'Right Basal Forebrain	 '; ...
 [37]  [4] 'Right ACgG'  'anterior cingulate gyrus	 '; ...
 [38]  [4] 'Left ACgG'   'anterior cingulate gyrus	 '; ...
 [39]  [4] 'Right AIns'  'anterior insula	'; ...
 [40]  [4] 'Left AIns'   'anterior insula	 '; ...
 [41]  [4] 'Right AOrG'  'anterior orbital gyrus	 '; ...
 [42]  [4] 'Left AOrG'   'anterior orbital gyrus	 '; ...
 [43]  [4] 'Right AnG'   'angular gyrus	 '; ...
 [44]  [4] 'Left AnG'    'angular gyrus	 '; ...
 [45]  [4] 'Right Calc'  'calcarine cortex	'; ...
 [46]  [4] 'Left Calc'   'calcarine cortex	'; ...
 [47]  [4] 'Right CO'    'central operculum	'; ...
 [48]  [4] 'Left CO'     'central operculum	'; ...
 [49]  [4] 'Right Cun'   'cuneus	'; ...
 [50]  [4] 'Left Cun'    'cuneus	'; ...
 [51]  [4] 'Right Ent'   'entorhinal area	'; ...
 [52]  [4] 'Left Ent'    'entorhinal area	 '; ...
 [53]  [4] 'Right FO'    'frontal operculum	'; ...
 [54]  [4] 'Left FO'     'frontal operculum	 '; ...
 [55]  [4] 'Right FRP'   'frontal pole	 '; ...
 [56]  [4] 'Left FRP'    'frontal pole	'; ...
 [57]  [4] 'Right FuG'   'fusiform gyrus	'; ...
 [58]  [4] 'Left FuG'    'fusiform gyrus	'; ...
 [59]  [4] 'Right GRe'   'gyrus rectus	'; ...
 [60]  [4] 'Left GRe'    'gyrus rectus	'; ...
 [61]  [4] 'Right IOG'   'inferior occipital gyrus'; ...
 [62]  [4] 'Left IOG'    'inferior occipital gyrus	'; ...
 [63]  [4] 'Right ITG'   'inferior temporal gyrus	'; ...
 [64]  [4] 'Left ITG'    'inferior temporal gyrus'; ...
 [65]  [4] 'Right LiG'   'lingual gyrus	'; ...
 [66]  [4] 'Left LiG'    'lingual gyrus	'; ...
 [67]  [4] 'Right LOrG'  'lateral orbital gyrus	'; ...
 [68]  [4] 'Left LOrG'   'lateral orbital gyrus	 '; ...
 [69]  [4] 'Right MCgG'  'middle cingulate gyrus	 '; ...
 [70]  [4] 'Left MCgG'   'middle cingulate gyrus	'; ...
 [71]  [4] 'Right MFC'   'medial frontal cortex	'; ...
 [72]  [4] 'Left MFC'    'medial frontal cortex	'; ...
 [73]  [4] 'Right MFG'   'middle frontal gyrus'; ...
 [74]  [4] 'Left MFG'    'middle frontal gyrus	 '; ...
 [75]  [4] 'Right MOG'   'middle occipital gyrus	 '; ...
 [76]  [4] 'Left MOG'    'middle occipital gyrus	 '; ...
 [77]  [4] 'Right MOrG'  'medial orbital gyrus	'; ...
 [78]  [4] 'Left MOrG'   'medial orbital gyrus	'; ...
 [79]  [4] 'Right MPoG'  'postcentral gyrus medial segment	'; ...
 [80]  [4] 'Left MPoG'   'postcentral gyrus medial segment	'; ...
 [81]  [4] 'Right MPrG'  'precentral gyrus medial segment	'; ...
 [82]  [4] 'Left MPrG'   'precentral gyrus medial segment	'; ...
 [83]  [4] 'Right MSFG'  'superior frontal gyrus medial segment	 '; ...
 [84]  [4] 'Left MSFG'   'superior frontal gyrus medial segment	 '; ...
 [85]  [4] 'Right MTG'   'middle temporal gyrus	 '; ...
 [86]  [4] 'Left MTG'    'middle temporal gyrus	 '; ...
 [87]  [4] 'Right OCP'   'occipital pole	'; ...
 [88]  [4] 'Left OCP'    'occipital pole	'; ...
 [89]  [4] 'Right OFuG'  'occipital fusiform gyrus	'; ...
 [90]  [4] 'Left OFuG'   'occipital fusiform gyrus	'; ...
 [91]  [4] 'Right OpIFG' 'opercular part of the inferior frontal gyrus	 '; ...
 [92]  [4] 'Left OpIFG'  'opercular part of the inferior frontal gyrus	 '; ...
 [93]  [4] 'Right OrIFG' 'orbital part of the inferior frontal gyrus	'; ...
 [94]  [4] 'Left OrIFG'  'orbital part of the inferior frontal gyrus	'; ...
 [95]  [4] 'Right PCgG'  'posterior cingulate gyrus	'; ...
 [96]  [4] 'Left PCgG'   'posterior cingulate gyrus	'; ...
 [97]  [4] 'Right PCu'   'precuneus	 '; ...
 [98]  [4] 'Left PCu'    'precuneus	 '; ...
 [99]  [4] 'Right PHG'   'parahippocampal gyrus	'; ...
 [100] [4] 'Left PHG'   'parahippocampal gyrus	 '; ...
 [101] [4] 'Right PIns'  'posterior insula	'; ...
 [102] [4] 'Left PIns'   'posterior insula	 '; ...
 [103] [4] 'Right PO'    'parietal operculum	'; ...
 [104] [4] 'Left PO'     'parietal operculum	'; ...
 [105] [4] 'Right PoG'   'postcentral gyrus	'; ...
 [106] [4] 'Left PoG'    'postcentral gyrus	'; ...
 [107] [4] 'Right POrG'  'posterior orbital gyrus	'; ...
 [108] [4] 'Left POrG'   'posterior orbital gyrus	'; ...
 [109] [4] 'Right PP'    'planum polare	 '; ...
 [110] [4] 'Left PP'     'planum polare	'; ...
 [111] [4] 'Right PrG'   'precentral gyrus	 '; ...
 [112] [4] 'Left PrG'    'precentral gyrus	'; ...
 [113] [4] 'Right PT'    'planum temporale	'; ...
 [114] [4] 'Left PT'     'planum temporale	'; ...
 [115] [4] 'Right SCA'   'subcallosal area	'; ...
 [116] [4] 'Left SCA'    'subcallosal area	'; ...
 [117] [4] 'Right SFG'   'superior frontal gyrus	'; ...
 [118] [4] 'Left SFG'    'superior frontal gyrus	'; ...
 [119] [4] 'Right SMC'   'supplementary motor cortex	'; ...
 [120] [4] 'Left SMC'    'supplementary motor cortex	 '; ...
 [121] [4] 'Right SMG'   'supramarginal gyrus	'; ...
 [122] [4] 'Left SMG'    'supramarginal gyrus	'; ...
 [123] [4] 'Right SOG'   'superior occipital gyrus	'; ...
 [124] [4] 'Left SOG'    'superior occipital gyrus	'; ...
 [125] [4] 'Right SPL'   'superior parietal lobule	'; ...
 [126] [4] 'Left SPL'    'superior parietal lobule	'; ...
 [127] [4] 'Right STG'   'superior temporal gyrus	'; ...
 [128] [4] 'Left STG'    'superior temporal gyrus	'; ...
 [129] [4] 'Right TMP'   'temporal pole	 '; ...
 [130] [4] 'Left TMP'    'temporal pole	'; ...
 [131] [4] 'Right TrIFG' 'triangular part of the inferior frontal gyrus	'; ...
 [132] [4] 'Left TrIFG'  'triangular part of the inferior frontal gyrus	 '; ...
 [133] [4] 'Right TTG'   'transverse temporal gyrus	 '; ...
 [134] [4] 'Left TTG'    'transverse temporal gyrus'; ...
 [135] [5] 'Sulcal CSF'  'intra-sulcal csf'};
end
